/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppMyCyberbackersRouteImport } from './routes/_app.my-cyberbackers'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app.knowledge-base'
import { Route as AppContractsRouteImport } from './routes/_app.contracts'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppMyCyberbackersRoute = AppMyCyberbackersRouteImport.update({
  id: '/my-cyberbackers',
  path: '/my-cyberbackers',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/billing': typeof AppBillingRoute
  '/contracts': typeof AppContractsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/my-cyberbackers': typeof AppMyCyberbackersRoute
  '/performance': typeof AppPerformanceRoute
  '/support': typeof AppSupportRoute
}
export interface FileRoutesByTo {
  '/attendance': typeof AppAttendanceRoute
  '/billing': typeof AppBillingRoute
  '/contracts': typeof AppContractsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/my-cyberbackers': typeof AppMyCyberbackersRoute
  '/performance': typeof AppPerformanceRoute
  '/support': typeof AppSupportRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/contracts': typeof AppContractsRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/my-cyberbackers': typeof AppMyCyberbackersRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/billing'
    | '/contracts'
    | '/knowledge-base'
    | '/marketplace'
    | '/my-cyberbackers'
    | '/performance'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/attendance'
    | '/billing'
    | '/contracts'
    | '/knowledge-base'
    | '/marketplace'
    | '/my-cyberbackers'
    | '/performance'
    | '/support'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/attendance'
    | '/_app/billing'
    | '/_app/contracts'
    | '/_app/knowledge-base'
    | '/_app/marketplace'
    | '/_app/my-cyberbackers'
    | '/_app/performance'
    | '/_app/support'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-cyberbackers': {
      id: '/_app/my-cyberbackers'
      path: '/my-cyberbackers'
      fullPath: '/my-cyberbackers'
      preLoaderRoute: typeof AppMyCyberbackersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts': {
      id: '/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBillingRoute: typeof AppBillingRoute
  AppContractsRoute: typeof AppContractsRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMyCyberbackersRoute: typeof AppMyCyberbackersRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppBillingRoute: AppBillingRoute,
  AppContractsRoute: AppContractsRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMyCyberbackersRoute: AppMyCyberbackersRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
